### ISSUE TITLE
ci: triggers of Build CI

### ISSUE THREAD

**Issue by hwakabh** [hwakabh/hwakabh.github.io#130]
## AsIs
Currently we have configured workflow triggers in Build CI with:
```yaml
on:
  pull_request:
    paths:
      - 'api-server/**'
      - 'web-frontend/**'
  workflow_dispatch:
```

Basically this works as we expected but Build CI would be also triggered when `git-pr-release` would create/update release PR, and this might be a duplication of workflow runnings.

<img width="1108" alt="Screenshot 2024-02-13 at 0 25 01" src="https://github.com/hwakabh/hwakabh.github.io/assets/25563897/4f316805-c2b9-4642-81f5-55dc144a7cb3">

## ToDo
- [x] Update workflow triggers in Build CI using [`on.pull_request.branches`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-based-on-the-head-or-base-branch-of-a-pull-request)

## (Optional) Acceptance
- [x] Build CI will NOT be triggered when we merge topic PR into `main`
