### ISSUE TITLE
ci: export paths-filter configs

### ISSUE THREAD

**Issue by hwakabh** [hwakabh/hwakabh.github.io#135]
## AsIs
Currently we put conditions for paths-filter with file path matches directly into `with.filters` inputs, which have added in #129. Since it has a feature to read configs from another file like below, as noted in [README](https://github.com/dorny/paths-filter), it is much better to export them for future maintenances and simplicity of the pipeline.

```yaml
    - name: Check for app file changes
      uses: dorny/paths-filter@v2.11.1
      id: changes
      with:
        filters: .github/path-filter.yml
```

## ToDo
- [x] refactor with export configs of paths-filter

## (Optional) Acceptance
N/A
