### ISSUE TITLE
fix(ci): Build CI triggers

### ISSUE THREAD

**Issue by hwakabh** [hwakabh/hwakabh.github.io#173]
## Descriptions
Currently we have following configurations with Build CI, but it seems this has not worked properly.

```yaml
name: Build CI

on:
  pull_request:
    branches:
      - '**'
      - '!main'
      - '!releases'
    paths:
      - 'api-server/**'
      - 'web-frontend/**'
  workflow_dispatch:
```

## Current Behavior
When we updated topic PR in https://github.com/hwakabh/hwakabh.github.io/pull/166, checks of build CI had not been triggered.

## Expected Bahavior
Since #166 has changes with application code, the build CI should be triggered in every commits update.

## Acceptance Criteria
When we will raise/update topic PR which contains code changes in application code, the build CI will be invoked.
